# SPDX-License-Identifier GPL-2.0+
---
# Our sensible defaults for the blktests role.
#
# We default to not run tests.
kdevops_run_blktests: False

# Ror instance you can use "-g quick" but note that this may produce
# not results as all quick tests may be expunded.
oscheck_extra_args: ""

blktests_git: "https://github.com/osandov/blktests.git"
blktets_data: "{{ data_path }}/blktests"
blktests_data_target: "/usr/local/blktests/"
blktests_test_devs: "/dev/null"
