# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
---
# tasks file for configuring ssmtp - modified kbrebanov.ssmtp
- name: Create sSMTP revaliases file
  become: yes
  become_method: sudo
  template:
    src: revaliases.j2
    dest: /etc/ssmtp/revaliases
    owner: root
    group: root
    mode: 0644
  tags: [ 'ssmtp', 'config' ]

- name: Create sSMTP configuration file
  become: yes
  become_method: sudo
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
  tags: [ 'ssmtp', 'config' ]
