# SPDX-License-Identifier GPL-2.0+ OR MIT
---
# tasks file for configuring the watchdog - whiskerlabs.watchdog
- name: configure watchdog daemon
  become: yes
  become_method: sudo
  template:
    src: watchdog.conf.j2
    dest: /etc/watchdog.conf
  notify: restart watchdog daemon
  tags: [ 'watchdog', 'config' ]
