---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- include: tasks/install-deps/main.yml

# Distro agnostic
- include: tasks/configure-postfix.yml
  when:
    - workflow_install_postfix|bool

- include: tasks/configure-watchdog.yml
  when:
    - workflow_install_watchdog|bool
