---
# Install dependenciesfor oscheck on Debian
- name: Set up apt for Debian testing/unstable
  become: yes
  become_method: sudo
  template:
    src: debian/sources.list.testing-unstable
    dest: /etc/apt/sources.list
  tags: [ 'apt', 'config' ]

- name: Set pinning preference for debian testing over unstable
  become: yes
  become_method: sudo
  template:
    src: debian/apt-preferences
    dest: /etc/apt/preferences
  tags: [ 'apt', 'config' ]

- name: Install sSMTP packages from Debian unstable
  become: yes
  become_method: sudo
  apt:
    name:
      - ssmtp
    default_release: unstable
    state: latest
    update_cache: yes
  tags: [ 'ssmtp', 'deps' ]

- name: Install bsd-mailx to test mail settings
  become: yes
  become_method: sudo
  apt:
    name:
      - bsd-mailx
    state: latest
    update_cache: yes
  tags: [ 'bsd-mailx', 'deps' ]

- name: Install watchdog package from Debian unstable
  become: yes
  become_method: sudo
  apt:
    name:
      - watchdog
    default_release: unstable
    state: latest
    update_cache: yes
  tags: [ 'watchdog', 'deps' ]

- name: Install disk provisioning dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - nvme-cli
      - xfsprogs

- name: Install fstests build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - bison
      - flex
      - git
      - e2fsprogs
      - automake
      - gcc
      - libuuid1
      - quota
      - make
      - xfsprogs
      - gawk
      - uuid-runtime
      - acl
      - bc
      - dump
      - indent
      - libtool
      - lvm2
      - psmisc
      - sed
      - xfsdump
      - libacl1
      - libacl1-dev
      - libaio1
      - libaio-dev
      - uuid-dev
      - uuid-runtime
      - attr
      - libattr1
      - libattr1-dev
      - gdbm-l10n
      - libgdbm-dev
      - libssl-dev
      - xfslibs-dev
      - fio
      - dbench
      - libcap2-bin
    state: present
    update_cache: yes
  tags: [ 'fstests', 'deps' ]
