---
- name: Create and mount exported filesystem
  tags: [ 'nfsd' ]
  include_role:
    name: create_partition
  vars:
    disk_setup_device: "{{ nfsd_export_device }}"
    disk_setup_fstype: "{{ nfsd_export_fstype }}"
    disk_setup_label : "{{ nfsd_export_label }}"
    disk_setup_fs_opts: "{{ nfsd_export_fs_opts -L nfsd_export_label }}"
    disk_setup_path: "{{ nfsd_export_path }}"
    disk_setup_user: "{{ data_user }}"
    disk_setup_group: "{{ data_group }}"

- name: Make the exported filesystem a world-writeable sticky dir
  tags: [ 'nfsd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.file:
    path: "{{ nfsd_export_path }}"
    owner: root
    group: root
    mode: 01777

# FIXME: make a template that uses {{ export_path }}
- name: Create /etc/exports with an export for /exports
  tags: [ 'nfsd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Generate /etc/nfs.conf
  tags: [ 'nfsd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: 0644

- name: Start up nfsd
  tags: [ 'nfsd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.systemd:
    name: nfs-server.service
    state: reloaded
