---
- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: linux

- name: Install nvme tools
  become: yes
  become_method: sudo
  apt:
    name:
      - nvme-cli

# Remove this step when xfsdump is available again in testing repo
- name: Add debian stable repository into sources list for xfsdump
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb http://deb.debian.org/debian stable main
    state: present

- name: Install fstests build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - bison
      - flex
      - git
      - automake
      - gcc
      - libuuid1
      - quota
      - make
      - xfsprogs
      - xfsdump
      - e2fsprogs
      - btrfs-progs
      - gawk
      - uuid-runtime
      - acl
      - bc
      - dump
      - indent
      - libtool
      - lvm2
      - psmisc
      - sed
      - libacl1
      - libacl1-dev
      - libaio1
      - libaio-dev
      - uuid-dev
      - uuid-runtime
      - attr
      - libattr1
      - libattr1-dev
      - gdbm-l10n
      - libgdbm-dev
      - libssl-dev
      - xfslibs-dev
      - fio
      - libcap2-bin
      - libtool
    state: present
    update_cache: yes
  tags: [ 'fstests', 'deps' ]
