---
# Install dependencies on Debian
- name: Set up apt for Debian testing/unstable
  become: yes
  become_method: sudo
  template:
    src: debian/sources.list.testing-unstable
    dest: /etc/apt/sources.list
  tags: [ 'apt', 'config' ]

- name: Set pinning preference for debian testing over unstable
  become: yes
  become_method: sudo
  template:
    src: debian/apt-preferences
    dest: /etc/apt/preferences
  tags: [ 'apt', 'config' ]

- name: Install our generic dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - nvme-cli
      - bison
      - flex
      - git
      - e2fsprogs
      - xfsprogs
      - xfsdump
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - libtool
      - psmisc
      - sed
    state: present
    update_cache: yes
  tags: [ 'kdevops', 'deps' ]
