---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install CXL build deps
  include_tasks: install-deps/main.yml

- include_role:
    name: create_data_partition
  tags: [ 'ndctl', 'data_partition' ]

- name: git clone ndctl
  git:
    repo: "{{ ndctl_git }}"
    dest: "{{ ndctl_data }}"
    version: "{{ ndctl_version }}"
    update: yes
  tags: [ 'git', 'ndctl' ]

- name: run meson setup build for ndctl
  command: "meson setup build"
  tags: [ 'ndctl' ]
  args:
    chdir: "{{ ndctl_data }}"

- name: Enable unit tests as per meson
  command: "meson configure -Dtest=enabled -Ddestructive=enabled build"
  tags: [ 'ndctl' ]
  args:
    chdir: "{{ ndctl_data }}"

- name: run meson compile -C build for ndctl
  command: "meson compile -C build"
  tags: [ 'ndctl' ]
  args:
    chdir: "{{ ndctl_data }}"

- name: run meson install -C build
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "meson install -C build"
  tags: [ 'ndctl' ]
  args:
    chdir: "{{ ndctl_data }}"

- name: Load configfs module
  tags: [ 'ndctl', 'cxl-test-prep' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "modprobe configfs"
  when:
    - kdevops_run_cxl_tests|bool

- name: Enable low-level messages on console
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: sysctl kernel.printk="8 8 1 7"
  tags: [ 'ndctl', 'cxl-test-prep' ]
  when:
    - kdevops_run_cxl_tests|bool

- name: modprobe cxl_test
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "modprobe cxl_test"
  tags: [ 'ndctl', 'cxl-test-probe' ]
  args:
    chdir: "{{ ndctl_data }}"
  when:
    - kdevops_run_cxl_tests|bool

- name: modprobe -r cxl_test
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "modprobe -r cxl_test"
  tags: [ 'ndctl', 'cxl-test-probe' ]
  args:
    chdir: "{{ ndctl_data }}"
  when:
    - kdevops_run_cxl_tests|bool

- name: run meson cxl unit test suite
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ignore_errors: yes
  no_log: True
  command: "meson test -C build --suite cxl"
  tags: [ 'ndctl', 'cxl-test-meson' ]
  args:
    chdir: "{{ ndctl_data }}"
  when:
    - kdevops_run_cxl_tests|bool
