---
- name: Force dbench compilation on debian
  set_fact:
    compile_dbench: True

- name: Install dbench build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - git
      - automake
      - autoconf
      - gcc
      - libuuid1
      - quota
      - make
      - sed
      - libacl1
      - libacl1-dev
      - libaio1
      - libaio-dev
      - uuid-dev
      - uuid-runtime
      - attr
      - libattr1
      - libattr1-dev
      - gdbm-l10n
      - libgdbm-dev
      - libssl-dev
      - xfslibs-dev
      - libcap2-bin
      - libtool
      - pkg-config
      - libpopt-dev
      - libtirpc-dev
      - libtirpc3
      - xsltproc
      - libsmbclient-dev
      - libiscsi-dev
    state: present
    update_cache: yes
  tags: [ 'dbench', 'deps' ]
