---
- name: Install local dependencies for fstests command and control
  become: yes
  become_method: sudo
  apt:
    name:
      - python3-junitxml

- name: Install junitparser
  become: yes
  become_method: sudo
  pip:
    name:
      - junitparser
  when:
    - install_local_deps|bool
  tags: [ 'local_deps' ]
