---
- name: Install local dependencies for fstests command and control
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - python3-junitxml
      - python-pip

- name: Install junitparser
  become: yes
  become_method: sudo
  pip:
    name:
      - junitparser
  when:
    - install_local_deps|bool
  tags: [ 'local_deps' ]
