# SPDX-License-Identifier copyleft-next-0.3.1
---

# You can override these
terraform_version: "0.12.19"
force_install_if_present: False

# Ignores using distro packages and installs from zip file instead
force_install_zip: False
