---
- name: Install partition creation base tools
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - xfsprogs
      - e2fsprogs
      - btrfs-progs
